mrd-2329_file-management-integration: supporting documents now using …
ministryofjustice/make-recall-decision-api pull request #1017
Opened 2024-05-13 15:03 UTC by bills7281

…file management api

2024-05-15 09:27 UTC, DarrenW-HMPPS requested changes

2024-05-16 16:53 UTC, bills7281 commented on fake-document-management-api/mappings/document-management-download.json
> +    "status": 201,
Corrected!

2024-05-16 16:53 UTC, bills7281 commented on fake-document-management-api/mappings/document-management-delete.json
> +    "urlPattern": "/documents.*"
Corrected!

2024-05-16 16:53 UTC, bills7281 commented on fake-document-management-api/mappings/document-management-download.json
> +    "urlPattern": "/documents.*"
Corrected!

2024-05-16 16:53 UTC, bills7281 commented on fake-document-management-api/mappings/document-management-download.json
> +      "Content-Type": "application/octet-stream"
Corrected!

2024-05-16 16:54 UTC, bills7281 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/DocumentManagementClient.kt
> +      .header("Service-Name", "Consider a recall")
From the Slack chat it looks like this is ok now.

2024-05-16 16:54 UTC, bills7281 commented on src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt
> +      .withPath("/documents.*")
Corrected!

2024-05-16 16:54 UTC, bills7281 commented on src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt
> +      .withPath("/documents.*")
Corrected!

2024-05-16 16:54 UTC, bills7281 commented on src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt
> +      .withBody("")
Removed

2024-05-16 16:56 UTC, bills7281 commented on src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/SupportingDocumentControllerTest.kt
>    fun `retrieve supporting documents`() {
Yeh, good point. I didn't introduce this function in my PR, so would it be ok if I addressed it outside the scope if this work?

2024-05-17 12:34 UTC, DarrenW-HMPPS approved these changes

2024-05-17 13:01 UTC, merged