Mrd 2522 remove releases obj from get offender call
ministryofjustice/make-recall-decision-api pull request #1116
Opened 2024-12-10 11:29 UTC by MancRickster

Also linked to mrd 2515 return sentence release date from ppud

2024-12-10 13:41 UTC, ppmg requested changes

2024-12-10 13:41 UTC, ppmg commented on src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/recommendation/PpudOffender.kt
>    val releases: List<PpudRelease>?,
Why keep the field? Are we still using it somewhere?

2024-12-10 13:41 UTC, ppmg commented on src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/recommendation/PpudOffender.kt
>  data class PpudRelease(
Same here - do we need to keep the type?

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/mappings/search-PPCS_X098092.json
Won't this clash with the existing search-PPCS_X738925.json? They have the same pattern matcher.

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/__files/get-offender-X098095.json
> -            "dateOfRelease": "2013-02-02",
Should we not be keeping this as the new `releaseDate` field? Or do you deliberately want it not to have one?

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/__files/get-offender-X098092.json
> +        "releaseDate": "2005-05-12",
Should this be `2013-02-02` as it is in the existing release? Or are you changing it deliberately? My only concern would be whether e2e tests rely on the date in some way for one of the test cases.

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/__files/get-offender-X098092.json
>          "releases": [
Shouldn't the `releases`be removed?

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/__files/get-offender-X098092.json
>          "releases": [
And the same on line 75 of this file (GitHub won't let me comment on it because it's too far from changes you've made).

2024-12-10 13:41 UTC, ppmg commented on fake-delius-integration-api/__files/recommendation-model-X788206.json
This is identical to some of the other json files in this same folder, is that right? If so, is there any point in having duplicates instead of having the mapping entries pointing to the same json and only keep separate json files if we have differences?

2024-12-10 13:41 UTC, ppmg commented on fake-ppud-automation-api/__files/search-PPCS_X098092.json
Is there any point in having duplicates instead of having the mapping entries pointing to the same json and only keep separate json files if we have differences (i.e. remove this file and have the new `search-PPCS_X098092.json` file you're adding to the `mapping` folder point to `search-PPCS_X738925.json` instead)?

2024-12-11 10:45 UTC, MancRickster commented on fake-ppud-automation-api/mappings/search-PPCS_X098092.json
good spot, test removed

2024-12-11 14:45 UTC, ppmg commented on src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/recommendation/PpudOffender.kt
>    val releases: List<PpudRelease>?,
Discussed: kept because existing recommendations with releases will fail on retrieval otherwise.

2024-12-11 14:46 UTC, ppmg commented on fake-ppud-automation-api/__files/get-offender-X098092.json
> +        "releaseDate": "2005-05-12",
Discussed: it did not affect the tests.

2024-12-11 14:47 UTC, ppmg commented on fake-delius-integration-api/__files/recommendation-model-X788206.json
Discussed: keeping it this way for now, following the existing pattern. Will look into a clean-up when we're more familiar with the code.

2024-12-11 14:47 UTC, ppmg approved these changes
LGTM

2024-12-11 15:32 UTC, merged